import os
import sys
pp = os.path.realpath(__file__)
for _ in range(2):
    pp = os.path.dirname(pp)

#Add API root to path
sys.path.append(os.path.join(pp))

from utils.formatting import write_line, get_string_array, get_string_dict
from core.output_reader import ForcastOutputReader

from pathlib import Path
import subprocess
import datetime as dt   
import pandas as pd
import numpy as np

from FORCAsT_API.core.site import Site
from FORCAsT_API.core.chemistry import Chemistry
from FORCAsT_API.core.grid import VerticalGrid
from FORCAsT_API.core.canopy import Canopy
from FORCAsT_API.core.turbulence import Turbulence
from FORCAsT_API.core.radiation import Radiation
from FORCAsT_API.core.ecosystem import PlantParameters, ResistanceParameters
from FORCAsT_API.core.emissions import Emissions
from FORCAsT_API.core.initialConditions import InitialConditions
from FORCAsT_API.core.species_profiles import SpeciesProfiles
from FORCAsT_API.core.directory_manager import DirectoryManager


class ForcastModel:

    def __init__(
        self,
        model_start: dt.datetime,
        model_end: dt.datetime = None,
        site: Site = None,
        canopy : Canopy = None,
        chemistry: Chemistry = None,
        grid: VerticalGrid = None,
        plant: PlantParameters = None,
        turbulence: Turbulence = None,
        radiation: Radiation = None,
        emissions: Emissions = None,
        resistance: ResistanceParameters = None,
        initial_conditions: InitialConditions = None,
        species_profiles: SpeciesProfiles = None,
        directory_manager: DirectoryManager = None,
    ):
        """
        Initialise ForcastModel with strict type enforcement.

        All configuration blocks must be either:
        - Proper core class instances
        - or None
        """

        # -----------------------------
        # Model timing
        # -----------------------------
        if not isinstance(model_start, dt.datetime):
            raise TypeError("model_start must be a datetime.datetime object")

        self.model_start = model_start

        if model_end is None:
            model_end = model_start + dt.timedelta(hours=48)

        if not isinstance(model_end, dt.datetime):
            raise TypeError("model_end must be a datetime.datetime object")

        if model_end <= model_start:
            raise ValueError("model_end must be later than model_start")

        self.model_end = model_end

        # -----------------------------
        # Core configuration blocks
        # -----------------------------
        self.site               = self._ensure_instance(site, Site)
        self.chemistry          = self._ensure_instance(chemistry, Chemistry)
        self.grid               = self._ensure_instance(grid, VerticalGrid)
        self.canopy             = self._ensure_instance(canopy, Canopy)
        self.turbulence         = self._ensure_instance(turbulence, Turbulence)
        self.radiation          = self._ensure_instance(radiation, Radiation)
        self.plant              = self._ensure_instance(plant, PlantParameters)
        self.emissions          = self._ensure_instance(emissions, Emissions)
        self.resistance         = self._ensure_instance(resistance, ResistanceParameters)
        self.initial_conditions = self._ensure_instance(initial_conditions, InitialConditions)
        self.species_profiles   = self._ensure_instance(species_profiles, SpeciesProfiles)

        self.directory_manager  = self._ensure_instance(directory_manager, DirectoryManager)

    # ------------------------------------------------------
    # Helper conversion method
    # ------------------------------------------------------
    @staticmethod
    def _ensure_instance(obj, cls):
        """
        Ensure object is:
        - None
        - Instance of cls
        - Dictionary convertible to cls(**dict)
        """
        if obj is None:
            return None

        if isinstance(obj, cls):
            return obj

        if isinstance(obj, dict):
            try:
                return cls(**obj)
            except TypeError as e:
                raise TypeError(
                    f"Cannot convert dictionary to {cls.__name__}: {e}"
                )

        raise TypeError(
            f"Expected {cls.__name__}, dict, or None ? got {type(obj)}"
        )

    @classmethod
    def from_input_file(cls, input_file, directory_manager, run_dir,**kwargs):
        """
        Reconstruct model from FORCAsT input file.
        """
    
        # Parse your input file here
        config = cls.parse_input_file(input_file,**kwargs)
    
        model = cls(**config)
        model.directory_manager = directory_manager
        model.directory_manager.current_run_dir = run_dir
    
        return model

    @classmethod
    def parse_input_file(cls, input_file, simulation_timezone=None):
        """
        Parse FORCAsT inputn generated by write_input()
        and reconstruct configuration dictionary suitable
        for ForcastModel(**config)
        """
    
        input_file = Path(input_file)
    
        if not input_file.exists():
            raise FileNotFoundError(f"{input_file} not found.")
    
        with open(input_file, "r") as f:
            lines = f.readlines()
    
        # Helper to extract numeric values from a line
        def get_values(line):
            data = line.split("(")[0].strip()
            return data.split()
    
        # Helper to convert list of strings to float/int intelligently
        def convert_list(lst):
            out = []
            for v in lst:
                if v.lower() in [".true.", "true"]:
                    out.append(True)
                elif v.lower() in [".false.", "false"]:
                    out.append(False)
                else:
                    try:
                        if "." in v or "E" in v or "e" in v:
                            out.append(float(v))
                        else:
                            out.append(int(v))
                    except ValueError:
                        out.append(v)
            return out
    
        i = 0
    
        # -----------------------
        # DATE
        # -----------------------
        vals = convert_list(get_values(lines[i]))
        jday, year = vals[0], vals[1]
        model_start = dt.datetime(year, 1, 1) + dt.timedelta(days=jday - 1)
        if not simulation_timezone is None:
            model_start = pd.to_datetime(model_start).tz_localize(simulation_timezone)
        i += 1
    
        # -----------------------
        # SITE
        # -----------------------
        vals = convert_list(get_values(lines[i]))
        site = {
            "lat": vals[0],
            "lon": vals[1],
            "stdlng": vals[2],
        }
        i += 1
    
        # -----------------------
        # CHEMISTRY
        # -----------------------
        vals = convert_list(get_values(lines[i]))
        chemistry = {
            "ichem": vals[0],
            "impmpo": vals[1],
        }
        i += 1
    
        # -----------------------
        # GRID
        # -----------------------
        vals = convert_list(get_values(lines[i]))
        grid = {
            "hcpy": vals[0],
            "htr": vals[1],
            "levhtr": vals[2],
            "levcpy": vals[3],
            "delta": vals[4],
        }
        i += 1
    
        # -----------------------
        # SONICS
        # -----------------------
        vals = convert_list(get_values(lines[i]))
        site.update({
            "isonics": vals[0],
            "zobstow": vals[1],
            "zobstcpy": vals[2],
            "zmxd": vals[3],
        })
        i += 1
    
        # -----------------------
        # CANOPY
        # -----------------------
        vals = convert_list(get_values(lines[i]))
        canopy = {
            "height":grid["hcpy"],
            "LAI": vals[0],
            "sizelf": vals[1],
        }
        i += 1
    
        # LAD fractions
        canopy["df"] = convert_list(get_values(lines[i]))
        i += 1
    
        # -----------------------
        # TURBULENCE
        # -----------------------
        stable = convert_list(get_values(lines[i]))[0]
        turbulence = {"stable": stable}
        i += 1
    
        vals = convert_list(get_values(lines[i]))
        turbulence.update({
            "vgday": vals[0],
            "vgn": vals[1],
        })
        i += 1
    
        vals = convert_list(get_values(lines[i]))
        turbulence.update({
            "zrday": vals[0],
            "zrn": vals[1],
            "alphaday": vals[2],
            "alphan": vals[3],
        })
        i += 1
    
        # -----------------------
        # RADIATION
        # -----------------------
        radiation = {}
        vals = convert_list(get_values(lines[i]))
        radiation.update({
            "itot": vals[0],
            "jmax": vals[1],
            "jmin": vals[2],
            "dfmin": vals[3],
            "clump": vals[4],
            "kmax": vals[5],
        })
        i += 1
    
        vals = convert_list(get_values(lines[i]))
        radiation.update({
            "inrad": vals[0],
            "iwpm2": vals[1],
        })
        i += 1
    
        vals = convert_list(get_values(lines[i]))
        radiation.update({
            "ratiod": vals[0],
            "ration": vals[1],
        })
        i += 1
    
        vals = convert_list(get_values(lines[i]))
        radiation.update({
            "emis": vals[0],
            "emisol": vals[1],
        })
        i += 1
    
        vals = convert_list(get_values(lines[i]))
        radiation.update({
            "rsoil": vals[0:radiation["kmax"]],
            "rleaf": vals[radiation["kmax"]:2*radiation["kmax"]],
            "tleaf": vals[2*radiation["kmax"]:],
        })
        i += 1
    
        # -----------------------
        # PLANT
        # -----------------------
        plant = {}
        vals = convert_list(get_values(lines[i]))
        plant.update({
            "avisr": vals[0],
            "bvisr": vals[1],
            "cvisr": vals[2],
            "anirr": vals[3],
            "bnirr": vals[4],
            "cnirr": vals[5],
        })
        i += 1

        vals = convert_list(get_values(lines[i]))
        plant.update({
            "avist": vals[0],
            "bvist": vals[1],
            "cvist": vals[2],
            "anirt": vals[3],
            "bnirt": vals[4],
            "cnirt": vals[5],
        })
        i += 1

        vals = convert_list(get_values(lines[i]))
        plant.update({
            "ispher": vals[0],
            "nalpha": vals[1],
            "gr": vals[2:],
        })
        i += 1

        vals = convert_list(get_values(lines[i]))
        plant.update({
            "imunu": vals[0],
            "xmeu": vals[1],
            "xneu": vals[2],
        })
        i += 1

        vals = convert_list(get_values(lines[i]))
        plant.update({
            "imunu": vals[0],
            "xmeuaz": vals[1],
            "xneuaz": vals[2],
            "beta0": vals[3],
            "nbeta": vals[4],
        })
        i += 1
        
        # -----------------------
        # EMISSIONS
        # -----------------------
        emissions = {}
        emissions["EFsyn"] = convert_list(get_values(lines[i])); i += 1
        emissions["EFpl"] = convert_list(get_values(lines[i])); i += 1
        emissions["bexp"] = convert_list(get_values(lines[i])); i += 1
        emissions["EFno"] = convert_list(get_values(lines[i]))[0]; i += 1
   
        # -----------------------
        # RESISTANCE
        # -----------------------
        resistance = {}
        vals = convert_list(get_values(lines[i]))
        resistance.update({
            "rcut20": vals[0],
            "rsmin": vals[1],
            "anstom": vals[2],
            "radn": vals[3],
        })
        i += 1

        vals = convert_list(get_values(lines[i]))
        resistance.update({
            "trsopt": vals[0],
            "trsmax": vals[1],
            "trsmin": vals[2],
            "rsexp": vals[3],
            "rsm": vals[4],
        })
        i += 1

        vals = convert_list(get_values(lines[i]))
        resistance.update({
            "psi1": vals[0],
            "psi2": vals[1],
        })
        i += 1

        vals = convert_list(get_values(lines[i]))
        resistance.update({
            "rastom": vals[0],
            "d1": vals[1],
            "bkv": vals[2],
        })
        i += 1

        resistance["rroot"] = convert_list(get_values(lines[i]))[0]; i += 1
        resistance["aroot"] = convert_list(get_values(lines[i]))[0]; i += 1
    
        # -----------------------
        # INITIAL CONDITIONS
        # -----------------------
        initial_conditions = {}
        vals = convert_list(get_values(lines[i]))
        initial_conditions.update({
            "grndT0": vals[0],
            "towT0": vals[1],
            "lapse": vals[2],
        })
        i += 1
    
        initial_conditions["zs"] = convert_list(get_values(lines[i])); i += 1
    
        vals = convert_list(get_values(lines[i]))
        initial_conditions.update({
            "bd": vals[0],
            "sandfc": vals[1],
            "siltfc": vals[2],
            "clayfc": vals[3],
        })
        i += 1
    
        initial_conditions["eta"] = convert_list(get_values(lines[i])); i += 1
        initial_conditions["temps"] = convert_list(get_values(lines[i])); i += 1
    
        # -----------------------
        # Return structured config
        # -----------------------
        return {
            "model_start": model_start,
            "site": site,
            "chemistry": chemistry,
            "grid": grid,
            "canopy": canopy,
            "turbulence": turbulence,
            "radiation": radiation,
            "plant": plant,
            "emissions": emissions,
            "resistance": resistance,
            "initial_conditions": initial_conditions,
        }
   
    def write_input(self):
        input_file = self.directory_manager.get_input_file()
        f = open(input_file, "w+")

        # --- Date ---
        data = f"{self.model_start.strftime('%-j %Y')}"
        comment = f"(jday, iyear) ! {self.model_start.strftime('%d %b %Y')}"
        write_line(f, data, comment)

        # --- Site ---
        s = self.site.__dict__
        data = f"{s['lat']:.3f} {s['lon']:.3f} {s['stdlng']:.1f}"
        comment = "(xlat, xlong, stdlng) ! Site location, stdlng is the standard longitude for the timezone required"
        write_line(f, data, comment)


        # --- Chemistry ---
        c = self.chemistry.__dict__
        data = f"{c['ichem']:.0f} {c['impmpo']:.0f}"
        comment = "(ichem, impmpo) ! Chemistry mechanism switch: 0 CACM, 1 RACM-MIM, MPMPO switch: 0 off, 1 on"
        write_line(f, data, comment)

        # --- Grid ---
        g = self.grid.__dict__ 
        data = f"{g['hcpy']:.1f} {g['htr']:.1f} {g['levhtr']:.0f} {g['levcpy']:.0f} {g['delta']:.3f}"
        comment = "(hcpy, htr, levhtr, levcpy, del) ! Canopy height, trunk space height, top level of trunk spece, top level of canopy, parameter for grid spacing"
        write_line(f, data, comment)

        # --- Sonics ---
        data = f"{s['isonics']:.0f} {s['zobstow']:.1f} {s['zobstcpy']:.1f} {s['zmxd']:.1f}"
        comment = "(isonics, zobstow, zobstcpy, zmxd) ! Number of sonics measurement heights, above canopy observation height [m a.g.l.], in-canopy observation height [m a.g.l.] ,mixed layer height [m a.g.l.]"
        write_line(f, data, comment)

        # --- Canopy ---
        cpy = self.canopy.__dict__
        data = f"{cpy['LAI']:.2f} {cpy['sizelf']:.3f}"
        comment = "(tlai, sizelf) ! Total projected leaf area index [m m-2] and average size of a leaf [?]"
        write_line(f, data, comment)

        # --- LAD fractions ---
        df_string = get_string_array(self.canopy.get_crownspace_profile_LAI(self.grid), precision=2)
        write_line(f, df_string, "(df) ! Leaf area fractions per canopy layers")

        # --- Turbulence ---
        t = self.turbulence.__dict__
        stable = ".true." if t['stable'] else ".false."
        write_line(f, stable, "(stable) ! Strong variability in akh?")

        data = f"{t['vgday']:.1f} {t['vgn']:.1f}"
        write_line(f, data, "(vgday, vgn) ! Geostrophic wind (day, night)")

        data = f"{t['zrday']:.1f} {t['zrn']:.1f} {t['alphaday']:.1f} {t['alphan']:.1f}"
        write_line(f, data, "(zrday, zrn, alphaday, alphan) ! Roughness height (day, night) and wind profile parameters (day, night)")

        # --- Radiation ---
        r = self.radiation.__dict__
        data = f"{r['itot']:.0f} {r['jmax']:.0f} {r['jmin']:.0f} {r['dfmin']:.1f} {r['clump']:.1f} {r['kmax']:.0f}"
        write_line(f, data, "(itot, jmax, jmin, dfmin, clump, kmax) ! Number of leaf angle classes, maximum number of canopy layer (N/A), minimum number of anopy layers (N/A), thinnest leaf layer in terms of LAI units (N/A), clumping factor for canopy structur (1 is no clumping), ")

        data = f"{r['inrad']:.0f} {r['iwpm2']:.0f}"
        write_line(f, data, "(inrad, iwpm2) ! Read incoming radiation (inrad=1 SW/PAR, 2 LW, 3 SW/PAR+LW), in [w m-2] (iwpm2=1) or in [umoles m-2 s-2] (iwpm2=0)")

        data = f"{r['ratiod']:.2f} {r['ration']:.2f}"
        write_line(f, data, "(ratiod, ration) ! Modifiers for incoming radiation (only important if inrad=0)")

        data = f"{r['emis']:.2f} {r['emisol']:.2f}"
        write_line(f, data, "(emis, emisol) ! Leaf thermal emissivity, Soil thermal emissivity")

        tmp = (
            get_string_array(r['rsoil'], 2) +
            get_string_array(r['rleaf'], 2) +
            get_string_array(r['tleaf'], 2)
        )
        write_line(f, tmp, "(rsoil, rleaf, tleaf) ! Soil reflectance, leaf reflectance, leaf transmission; for visible, near near infrared, and thermal radiation")

        # --- Plant optical parameters ---
        p = self.plant.__dict__

        data = f"{p['avisr']:.2f} {p['bvisr']:.2f} {p['cvisr']:.2f} {p['anirr']:.2f} {p['bnirr']:.2f} {p['cnirr']:.2f}"
        write_line(f, data, "(avisr, bvisr, cvisr, anirr, bnirr, cnirr) ! Non Lambertian coeff for leaf reflectance")

        data = f"{p['avist']:.2f} {p['bvist']:.2f} {p['cvist']:.2f} {p['anirt']:.2f} {p['bnirt']:.2f} {p['cnirt']:.2f}"
        write_line(f, data, "(avist, bvist, cvist, anirt, bnirt, cnirt) ! Non Lambertian coeff for leaf transmittance")

        gr_string = get_string_array(p['gr'], 1)
        data = f"{p['ispher']} {p['nalpha']} {gr_string}"
        write_line(f, data, "(ispher, nalpha, gr) ! 1/0, assume spherical leaf angle dist/read leaf angle input, number of leaf angle classes input, frac. of leaf area in various leaf angle classes (read if ispher=0)")

        data = f"{p['imunu']} {p['xmeu']:.3f} {p['xneu']:.3f}"
        write_line(f, data, "(imunu, xmeu, xneu) ! Use gr and calc meu&neu, 1: meu&neu input directly to calc leaf angle dist, 2: mean and std dev of leaf angle dist. input; value of meu/mean angle of leaf angle dist (0=horizonal leaves); value of neu, std. dev. of leaf angle dist")

        data = f"{p['imunua']:.0f} {p['xmeuaz']:.1f} {p['xneuaz']:.1f} {p['beta0']:.2f} {p['nbeta']:.0f}"
        write_line(f, data, "(imunua, xmeuaz, xneuaz, beta0, nbeta) ! 0: Leaves symmetric about azimuth (meu=neu=1), 1: Mean and std. dev. of azimuth angle dist; mean of azimuth angle dist; std. dev. of azimuth angle; Angle of minimun in leaf area if azimuth dist is assymetric; number of azimuth angle classes")

        # --- Emissions ---
        e = self.emissions.__dict__

        write_line(f, get_string_dict(e['EFsyn'], e['EF_order'], "EFsyn", 3), "(EFsyn) ! Synthesis emissions factors [nmol m-2 s-1]")
        write_line(f, get_string_dict(e['EFpl'], e['EF_order'], "EFpl", 3), "(EFpl) ! Pool emissions factors [nmol m-2 s-1]")
        write_line(f, get_string_dict(e['bexp'], e['bexp_order'], "bexp", 3), "(bexp) ! exponential factor pool emissions")
        write_line(f, f"{e['EFno']:.3f}", "(EFno) ! Soil NO emssion factor [nmol m-2 s-1]")

        # --- Resistances ---
        rp = self.resistance.__dict__

        data = f"{rp['rcut20']:.1f} {rp['rsmin']:.1f} {rp['anstom']:.1f} {rp['radn']:.1f}"
        write_line(f, data, "(rcut20, rsmin, anstom, radn) ! Rs vs light")

        data = f"{rp['trsopt']:.1f} {rp['trsmax']:.1f} {rp['trsmin']:.1f} {rp['rsexp']:.1f} {rp['rsm']:.1f}"
        write_line(f, data, "(trsopt, trsmax, trsmin, rsexp, rsm) ! Rs vs temperature")

        data = f"{rp['psi1']:.1f} {rp['psi2']:.1f}"
        write_line(f, data, "(psi1, psi2) ! Leaf water pot. at which stomata begin to close [bar]; Leaf water pot. at which stomata are closed [bar]")

        data = f"{rp['rastom']:.1f} {rp['d1']:.1f} {rp['bkv']:.1f}"
        write_line(f, data, "(rastom, d1, bkv) ! Ratio of stomatal resistance on top to bottom of leaf; VPD for start of stomatal closure [mb]; Slope of stom. conduct. vs VPD func")

        write_line(f, f"{rp['rroot']:.1E}", "(rroot) ! Hydrolic root resistance [m4 kg-1 s-1]")
        write_line(f, f"{rp['aroot']:.1f}", "(aroot) ! Rooting depth coefficient, exponent on root length density vs depth")

        # --- Initial conditions ---
        ic = self.initial_conditions.__dict__

        data = f"{ic['grndT0']:.2f} {ic['towT0']:.2f} {ic['lapse']:.4f}"
        write_line(f, data, "(grndT0, towT0, lapse) ! Ground temperature [K], temperature at zobstow [K], temperature lapse rate [K m-1]")

        write_line(f, get_string_array(ic['zs'], 2), "(zs) ! Soil variables input depth")

        data = f"{ic['bd']:.2f} {ic['sandfc']:.2f} {ic['siltfc']:.2f} {ic['clayfc']:.2f}"
        write_line(f, data, "(bd, sandfc, siltfc, clayfc) ! Soil density and composition")

        write_line(f, get_string_array(ic['eta'], 3), "(eta) ! Initial soil water content")
        write_line(f, get_string_array(ic['temps'], 1), "(temps) ! Initial soil temperatures [K]")

        f.close()
        return input_file

    def write_species_profiles(self):
        if self.species_profiles is not None:
            path = self.directory_manager.get_data_dir() / "init_profiles.dat"
            self.species_profiles.write(path)
        return None

    def create_run(self, model_run):
        run_dir = self.directory_manager.create_run(model_run)
        return run_dir

    def update_initial_conditions(self, *args, **kwargs):
       """
       Update model.initial_conditions from external database.
       """
       if not "data" in kwargs.keys():
           self.initial_conditions.update_from_csv(
               model_date_start=self.model_start,
               *args,
               **kwargs
           )
       else:
           self.initial_conditions.update_from_dataframe(
               model_date_start=self.model_start,
               *args,
               **kwargs
           )
       return None


    def _check_boundary_conditions_for_nan(self, allow_all_nan_files=None):
        """
        Check boundary condition files for NaN values.
    
        Parameters
        ----------
        allow_all_nan_files : list or set, optional
            Filenames that are allowed to contain only NaN values.
    
        Raises
        ------
        ValueError
            If NaNs are found in non-allowed files, or mixed NaN/non-NaN data.
        """
    
        if allow_all_nan_files is None:
            allow_all_nan_files = set()
        else:
            allow_all_nan_files = set(allow_all_nan_files)
    
        run_dir = self.directory_manager.current_run_dir
    
        if run_dir is None:
            raise RuntimeError("No active run directory.")
    
        data_dir = run_dir / "data"
    
        if not data_dir.exists():
            raise FileNotFoundError("Boundary condition directory not found.")
    
        files_checked = []
    
        for file in data_dir.glob("*"):
    
            if not file.is_file():
                continue

            if "init_profiles.dat" == os.path.basename(file):
                continue
    
            try:
                df = pd.read_csv(file, delim_whitespace=True, header=None)
            except Exception as e:
                raise RuntimeError(f"Failed to read boundary file: {file}") from e
    
            has_nan = df.isna().values.any()
            all_nan = df.isna().values.all()
    
            # -------------------------------
            # Case 1: file is allowed to be all NaN
            # -------------------------------
            if file.name in allow_all_nan_files:
                if not all_nan:
                    raise ValueError(
                        f"{file.name} is expected to contain ONLY NaNs, "
                        f"but contains valid values."
                    )
    
            # -------------------------------
            # Case 2: file is NOT allowed to have NaNs
            # -------------------------------
            else:
                if has_nan:
                    nan_locs = np.argwhere(df.isna().values)
    
                    raise ValueError(
                        f"NaN values found in boundary condition file: {file.name}\n"
                        f"First occurrences (row, col): {nan_locs[:5]}"
                    )
    
            files_checked.append(file.name)
    
        if not files_checked:
            raise RuntimeError("No boundary condition files found to validate.")

    def run(self, executable=None, force: bool = False, list_boundary_conditions: list = ()):
        """
        Execute FORCAsT inside the run directory.
    
        Before execution, check whether the model has already successfully run.
        A successful run is determined by checking output files in run/out
        and verifying that the last time step equals:
    
            (self.model_end - self.model_start) - 30 minutes
    
        Parameters
        ----------
        executable : str, optional
            Name of executable inside run directory.
        force : bool
            If True, run model even if it appears completed.
        list_boundary_conditions : list of boundary_conditions objects
            If not empty, the boundary conditions will be fetched before running
    
        Returns
        -------
        Path to run directory out folder
        """
    
        run_dir = self.directory_manager.current_run_dir
    
        if run_dir is None:
            raise RuntimeError("No active run directory. Did you call create_run()?")
    
        out_dir = self.directory_manager.get_out_dir()
   
        if not force and out_dir.exists():
            if self._check_successful_run(out_dir):
                print(f"Model run {self.directory_manager.current_run_dir} already completed successfully. Skipping execution.")
                return out_dir
    
        # Ensure input file is written
        input_file = self.write_input()
        self.write_species_profiles()
        for bconditions in list_boundary_conditions:
            self.fetch_boundary_conditions(bconditions)
    
        # Default executable name
        if executable is None:
            executable = self.directory_manager.executable_name
    
        log_file = run_dir / "run.log"
        original_cwd = os.getcwd()
    
#        try:
        os.chdir(run_dir)
    
        self._check_boundary_conditions_for_nan()

        with open(log_file, "w") as log:
            subprocess.run(
                [f"./{executable}", str(input_file.name)],
                stdout=log,
                stderr=log,
                check=True
            )
#        except:
#            print(f"Issue running {self.directory_manager.current_run_dir}. Confirm boundary conditions or run manually.")

#        finally:
        os.chdir(original_cwd)
    
        return out_dir
    
    def _check_successful_run(self, out_dir):
        """
        Check whether FORCAsT run completed successfully
        by inspecting output files and validating final time.
        """
    
        expected_duration = ((self.model_end - self.model_start) - dt.timedelta(minutes=30)).total_seconds()
    
        # Possible output files and keyword arguments
        output_configs = {
            # Small meteorological outputs
            "cache_cpy.out": {
                "header_line": 0,
                "units_line": 1,
                "level_column": None,
            },
            "cache_met.out": {
                "header_line": 0,
                "units_line": 1,
                "level_column": None,
            },
            "cache_misc.out": {
                "metadata_line": 0,
                "header_line": 1,
                "units_line": 2,
                "level_column": None,
            },
    
            # Large chemistry fields
            "conc.out": {
                "header_line": 0,
                "units_line": None,
                "level_column": "Level",
            },
            "depn.out": {
                "header_line": 0,
                "units_line": None,
                "level_column": "Level",
            },
            "cacm_zmix.out": {
                "header_line": 0,
                "units_line": None,
                "level_column": "Level",
            },
        } 
        for fname, kwargs in output_configs.items():
            fpath = out_dir / fname
            if not fpath.exists():
                continue
    
            try:
                ds = self.read_output(fpath,**kwargs)
    
                # Make sure we get datetime objects
                sim_time = pd.to_datetime(ds.time.values)
                sim_duration = (sim_time.max() - sim_time.min()).total_seconds()
                if sim_duration == expected_duration:
                    return True
       
                else:
                    return False

            except Exception:
                continue
    
        return False

    def fetch_boundary_conditions(self, provider):
        provider.populate_data_directory(self)
        return None

    def read_output(self, filename, **reader_kwargs):
        reader = ForcastOutputReader(
            filepath=self.directory_manager.get_out_dir() / filename,
            model=self,
            **reader_kwargs
        )
        return reader.to_xarray()


